repos:
  - repo: https://github.com/codespell-project/codespell
    rev: v1.17.1
    hooks:
      - id: codespell
        args: 
          - "--quiet-level=2"
        exclude: >
          (?x)^(
              .*\.lock|
              .*\.scss
          )$


